server:
  port: 8099
  servlet:
    context-path: /Global-Event-Data

spring:
  application:
    name: Global-Event-Data
  #mysql数据库配置
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.240:3306/global_event?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  redis:
    database: 7
    host: 192.168.12.240
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  data:
#    mongodb:
#      uri: mongodb://root:bigdatapass@192.168.12.220:27017,192.168.12.221:27017,192.168.12.222:27017/?replicaSet=repl&readPreference=primaryPreferred&authSource=admin
#      database: globalEvent
    elasticsearch:
      repositories.enabled: true
      properties:
        path.home: /es
        transport.tcp.connect_timeout: 120s
      cluster-nodes: 192.168.12.220:9300,192.168.12.221:9300,192.168.12.222:9300
      cluster-name: yc-es
      indexName:
        newsIndex: hot_news_test_03
        eventIndex: hot_events_test_03
        entityIndex: hot_entity_test_03
        coEntityIndex: hot_co_events
        tempAIndex: part_a_temp
        partAIndex: test_a
        partBIndex: test_b

logging:
  config: classpath:logging-config.xml
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    org.springframework.data.elasticsearch.core: debug

swagger:
  show: true

time:
  cron: 0 30 * * * ?

kafka:
  monitor01:
    topic: globalevent_push_nlp_v0.5.1
    group: groupA
    nlpThresholdTime: 30
    bigDataThresholdTime: 120